version: "3"
services:

  node-app:
    image: node:14-buster-slim
    command: /bin/bash
    tty: true
    working_dir: /workspace
    volumes:
      - ./app:/workspace
      - node_modules:/workspace/node_modules

  mydql:
    image: mysql
    volumes:
    - mysql_data:/var/lib/mysql
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=rootpassword
    - MYSQL_DATABASE=mysql000db
    - MYSQL_USER=user
    - MYSQL_PASSWORD=password
    command: --character-set-server=utf8 --collation-server=utf8_general_ci --default-authentication-plugin=mysql_native_password
    ports:
    - 3306:3306

  redis:
    image: redis
    restart: always
    volumes:
    - redis_data:/data
    ports:
    - 6379:6379

  mongo:
    image: mongo
    restart: always
    environment:
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
    - 27017:27017
    volumes:
    - mongodb_data:/data/db
    - configdb_data:/data/configdb

  mongo-express:
    image: mongo-express
    restart: always
    ports:
    - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
    - mongo
    
volumes:
  mysql_data:
  redis_data:
  mongodb_data:
  configdb_data:
  node_modules: